# Generated by Django 4.1 on 2022-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctions_auction_rename_bids_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='startingBid',
            new_name='starting_bid',
        ),
    ]
