# Generated by Django 4.1 on 2022-08-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_rename_category_auction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='current_bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='auctionID',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='auctionID',
            new_name='auction_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='auctionID',
            new_name='auction_id',
        ),
    ]
