# Generated by Django 4.1 on 2022-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_starting_bid_auction_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
